### ISSUE TITLE
Identifier redeclared ‘result’

### ISSUE THREAD

**Issue by jokedebian** [zC4sTr0/delphi-autoupdater-gunbound#2]
I have two little error trying to build and compile 
![82e19b23-7469-4d71-941f-fe04cfe84d76](https://github.com/zC4sTr0/delphi-autoupdater-gunbound/assets/13124098/993aaea0-f08b-4dd2-a7e6-8eacdfc27b34)

**Comment by zC4sTr0** [comment]
Are you using delphi XE? Which build?

Please remove the result variable declaration

```
function Base64Str(psrc: pointer; L: integer): BString;
  {-Base64 string of memory block of length L pointed by psrc}
var
  q,r: integer;
  b0,b1,b2: byte;
  {$ifndef RESULT} //remove this line
    result: BString; //remove this line
  {$endif} //remove this line
begin
  result := '';
  if (L>0) and (psrc<>nil) then begin
    q := L div 3;
    r := L mod 3;
    while q>0 do begin
      b0 := pByte(psrc)^; inc(Ptr2Inc(psrc));
      b1 := pByte(psrc)^; inc(Ptr2Inc(psrc));
      b2 := pByte(psrc)^; inc(Ptr2Inc(psrc));
      result := result + CT64[(b0 shr 2) and $3f]
                       + CT64[((b0 shl 4) and $30) or ((b1 shr 4) and $0f)]
                       + CT64[((b1 shl 2) and $3c) or ((b2 shr 6) and $03)]
                       + CT64[b2 and $3f];
      dec(q);
    end;
    if r=2 then begin
      b0 := pByte(psrc)^; inc(Ptr2Inc(psrc));
      b1 := pByte(psrc)^;
      result := result + CT64[(b0 shr 2) and $3f]
                       + CT64[((b0 shl 4) and $30) or ((b1 shr 4) and $0f)]
                       + CT64[(b1 shl 2) and $3c]
                       + '=';
    end
    else if r=1 then begin
      b0 := pByte(psrc)^;
      result := result + CT64[(b0 shr 2) and $3f]
                       + CT64[(b0 shl 4) and $30]
                       + '==';
    end;
  end;
  {$ifndef RESULT}
    Base64Str := result;
  {$endif}
end;
```

**Comment by jokedebian** [comment]
Thanks for answering :D
I am using Delphi 11 with the link you provided in the description, I have overcome that error, however other errors appeared, maybe you can provide me with a version where I can compile without problems
![Screenshot 2023-06-16 145707](https://github.com/zC4sTr0/delphi-autoupdater-gunbound/assets/13124098/3d172aa2-cf78-4ab0-980b-e46f8a91a995)

**Comment by zC4sTr0** [comment]
Is it possible for the application you want to create to compile it with **Borland Delphi 7.0?**
If it's NOT possible, I can help you to change it in a way that works on Delphi 11.

**Comment by jokedebian** [comment]
Ok now I'm trying with Delphi 7 but when trying to compile the package abbrevia I get this error
![Screenshot 2023-06-17 053313](https://github.com/zC4sTr0/delphi-autoupdater-gunbound/assets/13124098/fffbe622-715f-4c10-b4d5-41375a814cf0)

**Comment by zC4sTr0** [comment]
The abbrevia component provided in your source was missing the complete code to compile.
I just commited a new verson of the updater with the complete Abbrevia component.

This version I just updated in this repository will work.
Try to install Abbrevia in the following link:
`` ..\Abbrevia\packages\Delphi 7\Abbrevia.dpk. ``

_To install ABBREVIA in Delphi, follow these steps:_

- Open all ABBREVIA packages (dpks) in Delphi.
- From the "Package" menu, select "Compile".
- If there are no errors, from the "Package" menu select "Install".
- If you see a dialog box asking if you want to rebuild the IDE, click "No".
- If you see a dialog box telling you that it's not a VCL component, just click "Ok"


**Please clone or pull the new source provided on this repository**
