### ISSUE TITLE
how to generate a filelist.dat content

### ISSUE THREAD

**Issue by jokedebian** [zC4sTr0/delphi-autoupdater-gunbound#4]
In trying to update a new files for testing purposes but I don’t know how generate this file content, you have a some generator for this purpose?

**Comment by zC4sTr0** [comment]
Filelist.dat documentation is missing.

It will be updated this week.

**Comment by zC4sTr0** [comment]
This issue is expected to be fixed in november

**Comment by zC4sTr0** [comment]
We just added filelist.dat documentation and examples in readme!

Gunprotect file hasher has been made public in this repo (also we will create another repository for it soon)

**Comment by zC4sTr0** [comment]
@jokedebian This site may also do the hash correctly. If it works, please let us know.

https://toolkitbay.com/tkb/tool/BLAKE2s_256


Sorry for the delay on fixing the issue
