### ISSUE TITLE
How to protect the updater?

### ISSUE THREAD

**Issue by jokedebian** [zC4sTr0/delphi-autoupdater-gunbound#7]
I need to restrict the execute of the NyxLauncher without before execute the Updater first. How I do it?

**Comment by samuelrizzo** [comment]
Hi @jokedebian, how's it going?

We've found a simple way to ensure that NyxLauncher only launches after the updater: by hooking a .dll into the launcher. Its job is straightforward: to check that a command line was used to open NyxLauncher.

So, if there is no command line, it means the launcher wasn't opened by the Updater, and you can terminate the process; if there is a command line, then it's all good.

It might not be the best method, but it still works for most players as of 2023.

I hope this helps you,
Bye,
Rizzo

**Comment by zC4sTr0** [comment]
@jokedebian if you have any more questions about how to do it please reply on this issue

The issue will be kept open for discussion
